
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>First-Time Farmers - Navigation Menu</title>
    <style>
        /* Basic styling for navigation bar */
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }
        nav {
            background-color: #333;
            overflow: hidden;
        }
        nav ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            display: flex;
        }
        nav li {
            flex: 1;
        }
        nav a {
            display: block;
            color: white;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }
        nav a:hover {
            background-color: #575757;
        }
        /* Page content styling */
        .content {
            padding: 20px;
        }
        h1 {
            color: #333;
        }
        .under-construction {
            color: #cc0000;
            font-weight: bold;
            font-size: 18px;
            margin-top: 15px;
        }
    </style>
</head>
<body>
    <!-- Navigation menu -->
    <nav>
        <ul>
            <li><a href="#about">About Us</a></li>
            <li><a href="#services">Services</a></li>
            <li><a href="#products">Products</a></li>
            <li><a href="#contact">Contact</a></li>
        </ul>
    </nav>

    <!-- About Us section with 4 menu links -->
    <div class="content" id="about">
        <h1>About Us</h1>
        <ul>
            <li><a href="#">Our Story</a> <span class="under-construction"> - Under Construction</span></li>
            <li><a href="#">Team</a> <span class="under-construction"> - Under Construction</span></li>
            <li><a href="#">Careers</a> <span class="under-construction"> - Under Construction</span></li>
            <li><a href="#">Mission & Vision</a> <span class="under-construction"> - Under Construction</span></li>
        </ul>
    </div>
    
</body>
</html>
